### ISSUE TITLE
Egypt taking the state of Dire Dawa (817)

### ISSUE THREAD

**Issue by AMCortes1** [team-eoanb/EoaNB#101]
**Description**
I'm not 100% certain as I wasn't paying much attention to the area but I noticed a state that was landlocked from the rest of Egypt had been taken, probably in a peace deal after they defeated Ethiopia in a war. I assume this is an issue with the peace deal . 

**Branch**
[[EoaNB:Ver-Tersus-(Optimization-and-Finishing-Pax)]]

**Reproduction**
Unsure, play as Egypt and defeat Ethiopia in the 1870s war if the issue is in the peace deal. 

**Expected behavior**
The state shouldn't have been annexed I assume. 

**Screenshots**
![image](https://user-images.githubusercontent.com/103889190/163721486-4b2bcdc6-ea7b-463f-95ca-a6cfd67e62d5.png)

**Comment by Vanadium-GITHUB** [comment]
You would think so, but actually historical.
