### ISSUE TITLE
Issues with Montenegro's FT

### ISSUE THREAD

**Issue by AMCortes1** [team-eoanb/EoaNB#104]
**Description**
There seems to be a few small problems with it. In the screenshots below the focus "Assassination of Knez Danilo" shows a generic question mark icon while "First Montenegrin Newspaper" has no icon at all. In the 2nd screenshot it shows that the last focus "Prepare for war" has no effect.

**Branch**
[[EoaNB:Ver-Tersus-(Optimization-and-Finishing-Pax)]]

**Reproduction**
Play as Montenegro

**Screenshots**
![image](https://user-images.githubusercontent.com/103889190/163800379-de94eb8b-1736-488f-be91-44d1d227b2d5.png)
![image](https://user-images.githubusercontent.com/103889190/163800520-a23a2f17-3ca6-455d-a031-2f24df9671ea.png)

**Comment by Vanadium-GITHUB** [comment]
Done
