### ISSUE TITLE
Remove "Unrest in Ireland" idea if Ireland becomes fully independent

### ISSUE THREAD

**Issue by AMCortes1** [team-eoanb/EoaNB#109]
**Description**
I believe I actually reported this before becoming a tester and the British Dev fixed it. Unsure why it is back. 

**Branch**
[[EoaNB:Ver-Tersus-(Optimization-and-Finishing-Pax)]]

**Screenshots**
![image](https://user-images.githubusercontent.com/103889190/164286734-7eaf52a0-0fbd-46ba-818e-7f719da29aac.png)
![image](https://user-images.githubusercontent.com/103889190/164286769-010e5a41-c0a1-4fd6-a470-88235d4db541.png)

**Comment by Sir-DEM0** [comment]
Should be fixed now - Also made balances to ensure Ireland don't win uprising.
