### ISSUE TITLE
French starting research: Electrics and Instruments. 

### ISSUE THREAD

**Issue by AMCortes1** [team-eoanb/EoaNB#111]
**Description**
I noticed how France had several parts of its research tree already researched at the start of the game, while others, which it should have too, aren't so I just thought I'd report the most obvious: the Electrics and Instruments. The Daguerreotype was literally invented in France and widely in use by the early 1850s, while the electrical telegrah (or at least a similar version of it) was also being used by 1857. I'm not sure if the smaller research boxes can be added custom country loc like the guns etc but if so, for France it would be called Foy–Breguet telegraph or simply "French Telegraph"

**Screenshots**
![image](https://user-images.githubusercontent.com/103889190/164896626-21972be6-c6f8-4164-a4f9-a8856df527ce.png)

**Comment by FloridaMayhem** [comment]
Fixed
