### ISSUE TITLE
Bato Sfez is Death! (sic) localisation issues.

### ISSUE THREAD

**Issue by AMCortes1** [team-eoanb/EoaNB#112]
**Description**
Event that triggers for France in September 1857. It is riddled with localisation issues. See pic below for my own proposed corrections using paint 

**Branch**
[[EoaNB:Ver-Tersus-(Optimization-and-Finishing-Pax)]]

**Screenshots**
![image](https://user-images.githubusercontent.com/103889190/164909018-d5b2c7d8-f067-4201-b4f4-3b383e644358.png)

**Comment by FloridaMayhem** [comment]
Fixed
