### ISSUE TITLE
French focus "Chatellereault Expansion" gives a loc-less event. 

### ISSUE THREAD

**Issue by AMCortes1** [team-eoanb/EoaNB#113]
**Description**
The French focus "Chatellereault Expansion" in the starting Focus Tree gives a loc-less event. 

**Branch**
[[EoaNB:Ver-Tersus-(Optimization-and-Finishing-Pax)]]

**Screenshots**
![image](https://user-images.githubusercontent.com/103889190/164909587-1f1ddc51-8aa6-4ffc-813e-e6c1949404fb.png)

**Comment by FloridaMayhem** [comment]
Fixed
