### ISSUE TITLE
French fleet bombs Tunis - Pre event issue. 

### ISSUE THREAD

**Issue by AMCortes1** [team-eoanb/EoaNB#114]
**Description**
The event that only France can see that spawns the "French fleet bombs Tunis" news event is also riddled with localisation issues, mostly the lack of use of Capital Letters. It also lacks the election localisation. 

**Branch**
[[EoaNB:Ver-Tersus-(Optimization-and-Finishing-Pax)]]

**Screenshots**
![image](https://user-images.githubusercontent.com/103889190/164911030-01357bc3-11eb-49ec-8617-487c2c0c94a7.png)

**Comment by WorldMapperusV** [comment]
Should be fixed should be fixed now with the patch (Fixed Issue 114)
