### ISSUE TITLE
"Learn from the Italian Intervention" shouldn't be available if France doesn't intervene. 

### ISSUE THREAD

**Issue by AMCortes1** [team-eoanb/EoaNB#116]
**Description**
This focus is found in the Authoritarian branch of the French Focus tree. Seeing how now there's a chance for France to be left out of the wars, this focus should be locked behind a trigger. The player should be given another way to get rid of "Amateur Tacticians" idea, maybe via the colonisation of Vietnam. 

**Branch**
[[EoaNB:Ver-Tersus-(Optimization-and-Finishing-Pax)]]

**Reproduction**
Play as France, don't take part in the 2nd Independence War. 

**Screenshots**
![image](https://user-images.githubusercontent.com/103889190/164934027-292b37c5-0c78-4915-8c22-1810c83ca1a6.png)

**Comment by Imperialism1** [comment]
Added a temporary fix, some alternative method to remove that idea should probably be added at some point
