### ISSUE TITLE
Small typos in the Sepoy focus

### ISSUE THREAD

**Issue by AMCortes1** [team-eoanb/EoaNB#117]
**Description**
The focus "Force cohesion with the army" should be "Force Cohesion within the army".
The focus "Bring the Sikhs on Side" should be "Bring the Sikhs to our side".

**Branch**
[[EoaNB:Ver-Tersus-(Optimization-and-Finishing-Pax)]]

**Screenshots**
![image](https://user-images.githubusercontent.com/103889190/165283405-5c549c00-5519-40d5-96f1-998c49988877.png)
![image](https://user-images.githubusercontent.com/103889190/165283529-6b44ad6a-2f63-49d9-a40c-374f234b3656.png)

**Comment by Sir-DEM0** [comment]
Changes Made
