### ISSUE TITLE
"Restructure Kouppas" Greek focus has no effects.

### ISSUE THREAD

**Issue by AMCortes1** [team-eoanb/EoaNB#119]
**Description**
The "Restructure Kouppas" focus of the first Greek tree has no effects.

**Branch**
[[EoaNB:Ver-Tersus-(Optimization-and-Finishing-Pax)]]

**Screenshots**
![image](https://user-images.githubusercontent.com/103889190/165493568-2f41c87a-6eed-4b96-a3dd-d1a442335f36.png)

**Comment by discordgr** [comment]
Made a small fix to push for VT and will re-evaluate the focus in a later date as i'm currently on hiatus
