### ISSUE TITLE
Leader of Andorra portrait broken.

### ISSUE THREAD

**Issue by AMCortes1** [team-eoanb/EoaNB#120]
**Description**
There is no portrait for the leader of Andorra.

**Branch**
[[EoaNB:Ver-Tersus-(Optimization-and-Finishing-Pax)]]

**Screenshots**
![image](https://user-images.githubusercontent.com/103889190/165506647-8d21ff94-6b9c-4ac1-b8bf-443e6850f745.png)

**Comment by Sir-DEM0** [comment]
Changes Made
