### ISSUE TITLE
Collapse of the Qing doesn't transfer southern states to Ming.

### ISSUE THREAD

**Issue by AMCortes1** [team-eoanb/EoaNB#123]
**Description**
I recall that it used to transfer those lands to the Ming. However, now I've noticed it doesn't transfer some, still cores of the Qing Pretender State.

**Branch**
Eg. Experimental. Use "Steam" if you're on steam.

**Reproduction**
Lose as the Qing. 

**Expected behavior**
States should be given to Ming or the Wu Lingyun rebellion, which holds cores right there too. 

**Screenshots**
![image](https://user-images.githubusercontent.com/103889190/165796245-b01e9441-3ec5-4b90-9f4c-d8d42e2a2603.png)

**Comment by Vanadium-GITHUB** [comment]
I think the condition was that Dacheng had died no land would give to Dacheng, but Garion should definitely add these as possible given to Wu
