### ISSUE TITLE
Mod isnt showing up in the new launcher

### ISSUE THREAD

**Issue by NeoEx0** [team-eoanb/EoaNB#13]
Just  tried to play the mod(yes i did copie the toi fileand toi folder to Documents/Paradox Interactive/Hearts of Iron IV/mod) but it doesent show up in the Launcher.
i already Tried relaunching the launcher but still nothing.
i also tested if the launcher is even knows its there and the anwnser s no, the number of totale mods installed  doesent change when the mod is copied to the mods folder/ deleted from it

**Comment by RandomGuy45678** [comment]
Hello, I am not a developer, but try opening toi.mod in a text editor (I am not sure whether Microsoft Notepad can change the encoding, but in case it can't, I personally recommend Notepad++) and changing the encoding to UTF-8 without BOM, it has worked for me before. As of 1.8, .mod files encoded in UTF-8 with BOM aren't supported, and the EoaNB developers should have changed the encoding of the .mod files.

**Comment by NeoEx0** [comment]
Thx it worked
