### ISSUE TITLE
Colour is changed for the USA but not for the Post-Civil War Reconstruction Puppets.

### ISSUE THREAD

**Issue by AMCortes1** [team-eoanb/EoaNB#133]
**Description**
I think these should be same colour too.

**Branch**
[[EoaNB:VT-Hotfix]]

**Screenshots**
![image](https://user-images.githubusercontent.com/103889190/167170052-9ac10046-8c0a-48ec-bfc8-01845dda3045.png)

**Comment by Barendd1975** [comment]
Colors have been changed to reflect main US color
