### ISSUE TITLE
"Suez Canal Construction" decision should disappear eventually. 

### ISSUE THREAD

**Issue by AMCortes1** [team-eoanb/EoaNB#134]
**Description**
I helped build the Suez like 10 years ago and the decision is still there, completed. Seeing how there's a lot of decisions for me (Austria) to click through, having the completed ones removed would help navigate the decision tab. Maybe have it disappear after a year or so, enough for the player to notice it's been completed. 

**Branch**
[[EoaNB:VT-Hotfix]]

**Screenshots**
![image](https://user-images.githubusercontent.com/103889190/167175819-bd2f9ede-13f2-4bc0-bdb2-803c84588380.png)

**Comment by Garion132** [comment]
it hanging around is important for later content
