### ISSUE TITLE
British decisions to annex Indian States into the British Raj disappear after completing one of them

### ISSUE THREAD

**Issue by AMCortes1** [team-eoanb/EoaNB#153]
**Description**
The British have decisions that remove the Puppet from the Indian Puppets and declares war on them to annex them into the Raj. However, after one gets completed the decission disappears from the British Decision tab, leaving the other Puppets stuck there forever. 

**Branch**
[[EoaNB:VT-Hotfix]]

**Reproduction**
Play as the UK
Defeat the Sepoys
Do the decision

**Screenshots**
Screenshot from before the decisions have been chosen:
![image](https://user-images.githubusercontent.com/103889190/168481060-01d1d295-9c47-46af-a931-8b5d12dbace1.png)
Now they're gone:
![image](https://user-images.githubusercontent.com/103889190/168481337-e9c8a1e4-864c-4d77-a0f3-02f909787771.png)

**Comment by Sir-DEM0** [comment]
Issue did not occur after multiple tries.
