### ISSUE TITLE
Some CSA generals have blanked portraits. 

### ISSUE THREAD

**Issue by AMCortes1** [team-eoanb/EoaNB#155]
**Description**
See screenshots.

**Screenshots**
![image](https://user-images.githubusercontent.com/103889190/168486127-c5cef04c-3c2c-40fa-823e-99748ea29b54.png)
![image](https://user-images.githubusercontent.com/103889190/168486144-ed5d3dcd-4e9d-451c-9309-1923c3228417.png)

**Comment by Imperialism1** [comment]
Unless I'm mistaken, Funky and Energy solved this.
