### ISSUE TITLE
Civil War Victory Event Not Firing

### ISSUE THREAD

**Issue by Ormr1** [team-eoanb/EoaNB#16]
Pretty self-explanatory. I've won the Civil War as the Union yet the event didn't fire and I'm unable to go down the Victorious Reconstruction focus tree.

Proof that I have won the Civil War is posted here as well.
![20200126115707_1](https://user-images.githubusercontent.com/45299815/73139381-2961b380-4033-11ea-82bf-6851942f730c.jpg)

**Comment by MaxehHere** [comment]
Well, I can't help, but what you can do in the meantime is run these 2 commands-
focus.autocomplete
focus.nochecks
Then, once you finish the first focus, you can run said two commands again and you should be good to go.
