### ISSUE TITLE
Post Russo-Turkish War (Historical) countries lack portraits and leaders.

### ISSUE THREAD

**Issue by AMCortes1** [team-eoanb/EoaNB#160]
**Description**
The following countries lack leaders/portraits: Eastern Rumelia (No portrait), Bulgaria (No leader, no portrait), Prizren League (No portrait) and Bosnia (No portrait). They could also get some starting ideas to let the player know a bit about each's situation even if they're not playing as them.

![image](https://user-images.githubusercontent.com/103889190/169348230-2a21626b-5906-4d67-8ff9-9eae29cb3c63.png)
![image](https://user-images.githubusercontent.com/103889190/169348367-d3b5b72a-82d4-4e52-856e-ae8ff221e00f.png)

**Comment by Imperialism1** [comment]
Since this is just content that is still being developed, I'm going to close it for now. (afaik all of these will be rectified shortly)
