### ISSUE TITLE
Game Freeze on Suez Canal Completion

### ISSUE THREAD

**Issue by Eiszett** [team-eoanb/EoaNB#17]
I have tried reloading back a few days before this happens, to no avail. I get a popup saying that the Suez canal has been constructed, a French ship (l'Aigle?) has gone through, and then the speed can't be changed. I am using the main branch of the mod. Attached are two saves, one a few days before, and one after it froze.

[SuezSaves.zip](https://github.com/team-eoanb/EoaNB/files/4114638/SuezSaves.zip)

**Comment by Eiszett** [comment]
Apparently it just takes ten minutes to calculate all the Suez Canal stuff. It unfroze after I posted this.

**Comment by Garion132** [comment]
yea, not much we can do about that
