### ISSUE TITLE
As the US, I got three Mexican Generals

### ISSUE THREAD

**Issue by AMCortes1** [team-eoanb/EoaNB#183]
**Description**
As seen in the screenshots, I got three Mexican generals at around 1861. Not sure exactly why as I didn't get any events. One of them, 
José Santos Degollado should literally be dead, as he dies three days before my current date in Mexico. 

**Branch**
Ars Bellica

**Reproduction**
1- Play as the US
2- Moderately support the Liberals (I assume, if it is intentional.)
3-Have them lose and just wait.

**Expected behavior**
The US shouldn't get these generals.

**Screenshots**
![image](https://user-images.githubusercontent.com/103889190/182036638-19a86012-81a7-4d30-8c5c-5ae5e0904f11.png)
![image](https://user-images.githubusercontent.com/103889190/182036648-72feda96-1e30-4381-8ba9-85734026c509.png)

**Comment by Energywelder** [comment]
This is intended, bot a bug, if it should be changed that's different

**Comment by Imperialism1** [comment]
One of them is dead at the date they are received in this playthrough

**Comment by Imperialism1** [comment]
As stated in the issue "José Santos Degollado should literally be dead, as he dies three days before my current date in Mexico."

**Comment by Energywelder** [comment]
Mexican generals now die on time
