### ISSUE TITLE
Freeze

### ISSUE THREAD

**Issue by natfox09** [team-eoanb/EoaNB#19]
So far I have tried 1.8.2,1.8.1, and 1.8.0 but each time my game freezes as soon as I try to group troops under a specific commander. I am going to try one more thing but just wanted to get this conversation rolling.

**Comment by natfox09** [comment]
Update on this. It isn't limited to me grouping men under a single general. When I do any action this causes the game to freeze and me to close it. I have tried it with all the DLCs I have on and all of them off. Nothing has seemingly changed.

**Comment by natfox09** [comment]
the answer based on the other "solved issues" is going to talk about your discord. How do I find your discord?

**Comment by TPS-Geronam** [comment]
I am amazed by the fact that you found the GitHub but not the Discord.
Link is inside the workshop description.
