### ISSUE TITLE
Prussia white peace's Austria within a month so Italy is stuck at war with austria

### ISSUE THREAD

**Issue by LforLuke** [team-eoanb/EoaNB#28]
Prussia invaded Austria and me playing as Italy got the event to go to war, I accept however within a month Prussia white peace's with Austria leaving Italy with the entire Austrian army so I wasn't able to get the event to end the war because I was pushed back and eventually pupated.

**Comment by blackfed** [comment]
Got same thing, partially solved by joining Prussia’s faction when I joined the war. Just one problem, didn’t got Veneto when the war ended, had to annex it with commands, when the peace deal had to give it to me.
