### ISSUE TITLE
Suez Canal Issues

### ISSUE THREAD

**Issue by Vanadium-GITHUB** [team-eoanb/EoaNB#64]
**Describe the bug**
Some players are reporting that they cannot develop the Suez Canal

**Comment by Phaeton20** [comment]
Same Problem here:
Playing as Prussia on Steam latest build in April 1859. I accepted the possibility to participate in building the Suez Canal but didn't get more options
![EoaNB](https://user-images.githubusercontent.com/69821706/114742777-58556980-9d4c-11eb-8f4b-ed831005b86e.PNG)

**Comment by rollingamer** [comment]
saving & reloading the game seems to fix the problem.

**Comment by Vanadium-GITHUB** [comment]
Reworked and Fixed!
