### ISSUE TITLE
German Localisation not loading correctly

### ISSUE THREAD

**Issue by Phaeton20** [team-eoanb/EoaNB#70]
**Describe the bug**
If you load the have the launcher set on German, almost all hover over event decisons do not show any text aside from xxx_xxx_xxx_xxx with xxx as some text

**Which branch are you on**
Steam

**To Reproduce**

1. Set Launcher on "German"
2. Start a new Game
3. Already at Scenario there isn't a working description

**Expected behavior (if you know)**
Description, Focus, Research and event text loading

**Screenshots**

**Desktop (only enter if applicable):**
 - OS: Windows 10

**Additional context**

**Comment by Imperialism1** [comment]
Solution - don’t launch the game in German

**Comment by Phaeton20** [comment]
Ok, cause there where these generic titles I thought there was a german translation, which didn't work correctly
