### ISSUE TITLE
Bulgaria

### ISSUE THREAD

**Issue by Simchoo** [team-eoanb/EoaNB#71]
After the Russo-Turkish War of 1878 Bulgaria became a tributary state of the Ottoman Empire. On September 6, 1885 Bulgaria annexed Eastern Rumelia. On November 14, Serbia attacked Bulgaria. The leader of the Bulgarian state between 1878 and 1886 was Alexander Battenberg.

**Comment by Garion132** [comment]
well yes, we know that. currently bulgaria will get released if russia wins the russio-turkish war (or the uprising succeeds), and the eastern rumelia states becomes a demiliterised zone. eastern rumelia will be released as a ottoman puppet later with their interaction with bulgaria(and bulgarian content) being based on weather we get a bulgarian or balkan dev at some point.

**Comment by Simchoo** [comment]
Thanks for the response.
