### ISSUE TITLE
Reinstall the terrain folder.

### ISSUE THREAD

**Issue by RubenAG73** [team-eoanb/EoaNB#72]
I really recomend reinstalling the map/terrain folder, it makes the game look a lot better.

**Comment by Makkkkus** [comment]
What do you mean exactly?

**Comment by RubenAG73** [comment]
There is a folder in map, the terrain folder, if you copy it from HOI4 and use it instead of the one in the mod it makes it look a lot better.

**Comment by Makkkkus** [comment]
We can copy the textures, but not the colormaps or the city-lights.

@Garion132

**Comment by Makkkkus** [comment]
> 
> 
> There is a folder in map, the terrain folder, if you copy it from HOI4 and use it instead of the one in the mod it makes it look a lot better.

After checking, all the textures are from the basegame.

**Comment by RubenAG73** [comment]
![2021-06-03](https://user-images.githubusercontent.com/84998308/120646697-11e1d880-c47a-11eb-95af-2c11ca4d98a6.png)

**Comment by Makkkkus** [comment]
Yes, that is good

**Comment by Makkkkus** [comment]
It loads the textures from the basegame
