### ISSUE TITLE
CTD on click "Details" for any Admiral or General

### ISSUE THREAD

**Issue by joshpelz** [team-eoanb/EoaNB#91]
**Describe the bug**
Crash to desktop when clicking the "Details" button to view traits on any admiral or general 

**Which branch are you on**
Ver-Tersus-(Optimization-and-Finishing-Pax)
as of 26th November, 2021

**To Reproduce**
1. Start Single Player Game
2. Select any nation
3. Click "Officer Corps" button in nav bar
4. Select either Generals or Admirals to view leader list
5. Add new commander if none present, or on any existing commander:
6. Click "Details" button to view leader traits
>> crashes to desktop <<

**Expected behavior (if you know)**
Traits menu opens for the specified leader.

**Screenshots**

**Desktop (only enter if applicable):**
 - OS: Windows 10
 - Game Version 1.11.2 with all DLC

**Additional context**
The same crash occurs via the menus for adding a commander to a force on the map, selecting their portrait and clicking Details button on any leader.

**Comment by joshpelz** [comment]
Good news, looks like changes in [276fac7](https://github.com/team-eoanb/EoaNB/commit/276fac75a693ec255d4b5f26afe7275adfa41c32) fixed this overnight.

I have re-tested several times with no repro today at HEAD, reverted to [a0c04f0](https://github.com/team-eoanb/EoaNB/commit/a0c04f0fef8d72097d4645f6f625f6752d8fdc6b) and validated the crash _does_ occur there.

Many thanks to @Garion132 for the swift turn-around on this issue!

**Comment by Vanadium-GITHUB** [comment]
Thank you for the huge help!
